# SQLite. Versions 3.8.0 and up are supported.
#   gem install sqlite3
#
#   Ensure the SQLite 3 gem is defined in your Gemfile
#   gem 'sqlite3'
#
default: &default
  adapter: mysql2
  encoding: utf8
  pool: 5
  username: ROOT
  password:
  socket: /var/run/mysqld/mysqld.sock

development:
  <<: *default
  database: eshop_development

test:
  <<: *default
  database: eshop_test

production:
  <<: *default
  database: eshop_development_production
  username: ROOT
  password: